### PR TITLE
Update README.md to reposition the buymeacoffee button

### PR DESCRIPTION
**Pull request by raja-chaudhary**

### CODE REVIEW

**Review by tawhidmonowar — CHANGES_REQUESTED** [review]
It should be below Features section and above To Do section, also you can add the headline.

**Comment by tawhidmonowar** [comment]
Thank you for the PR, don't forget to give a star. Your star would help increase the visibility of the project.

**Comment by raja-chaudhary** [comment]
> It should be below Features section and above To Do section, also you can add the headline.

Updated

**Review by tawhidmonowar — APPROVED** [review]
Thnak you @raja-chaudhary

**Pull request merged**
